version: '3.8'

services:
  archimmich-web:
    build: .
    container_name: archimmich-web
    ports:
      - "8000:8000"
    volumes:
      # Map config directory to store config.json and log files
      - ./config:/config
      # Map downloads directory to store completed archives locally or on NAS storage
      - ./downloads:/downloads
    restart: unless-stopped
    environment:
      - ARCHIMMICH_CONFIG_DIR=/config
      - ARCHIMMICH_DOWNLOADS_DIR=/downloads
